baseURL = "https://www.sebastianschirmer.com/"
languageCode = "en-us"
title = "Sebastian Schirmer"
theme = "lio"

[params]
    author = "Sebastian Schirmer"
    description = "Sebastian Schirmer - UX Engineer / Frontend Developer"
    githubUsername = "SebastianSchirmer"
    font = "Rubik" # should match the name on Google Fonts! # Quicksand Rubik
    siteSubtitle = "UX Engineer / Frontend Developer"

### HIGHLIGHT JS ###
    highlightEnabled = true
    highlightStyle = "monokai-sublime"
    highlightLanguages = ["typescript", "xml", "css", "scss"]

#[[menu.main]]
#    url = "/"
#    name = "Home"
#    weight = 1

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

#[[menu.main]]
#    url = "/work/"
#    name = "Work"
#    weight = 2
#
#[[menu.main]]
#    url = "/about/"
#    name = "About"
#    weight = 3
#
#[[menu.main]]
#    url = "/contact/"
#    name = "Contact"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:sebastian.schirmer@quiply.com"
    name = "Email"
    pre = "envelope-o"
    weight = 1

#[[menu.icon]]
#    url = "https://github.com/SebastianSchirmer/"
#    name = "github"
#    weight = 2

[[menu.icon]]
    url = "https://twitter.com/LeSchirmeur/"
    name = "Twitter"
    pre = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/sebastian-schirmer-257a98b0/"
    name = "Linkedin"
    pre = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.xing.com/profile/Sebastian_Schirmer/"
    name = "Xing"
    pre = "xing"
    weight = 5
